Repository CloudGeometry/cg-devx-core, pull requests merged in 2024-05, with the labels that each got.

#60 feat(cli): enable support for Python 3.11 and 3.12
  tools/cli/commands/destroy.py
  tools/cli/commands/setup.py
  tools/cli/common/utils/k8s_utils.py
  tools/poetry.lock
  tools/pyproject.toml
Labels: enhancement

#62 docs: add links to official docs on gh pages
  QUICKSTART.md
  README.md
  platform/tpl_README.md
Labels: documentation

#61 feat: upgrade kubecost to v2.2.2
  platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/kubecost/kubecost.yaml
  tools/cli/commands/setup.py
  tools/cli/services/cloud/aws/aws_manager.py
  tools/cli/services/cloud/azure/azure_manager.py
  tools/cli/services/cloud/cloud_provider_manager.py
Labels: platform

#64 fix(cli): add default values for optional arguments in WorkloadManagement class
  tools/cli/commands/workload/bootstrap.py
  tools/cli/commands/workload/delete.py
  tools/cli/services/wl_template_manager.py
Labels: bug
